seed: 42
device: "cuda"
split_names: ["train_set", "test_set", "eval_set"]

dataset:
  name: "qanastek/MASSIVE"
  languages: ["en-US"]
  lang: "locale"
  text: "utt"
  label: "intent"
  num_labels: 60


# teacher1:
#   name: "FacebookAI/xlm-roberta-base"
#   epochs: 10
#   lr: 2.0e-5
#   decay: 0.01
#   patience: 3
#   batch_size: 32
#   output_dir: "outputs/checkpoints/teacher_xlmr"
#   warm-up: 0.1

teacher2:
  name: "FacebookAI/xlm-roberta-large"
  epochs: 15
  lr: 5.0e-6
  decay: 0.1
  patience: 5
  batch_size: 16
  output_dir: "outputs/checkpoints/teacher_xlmr2"
  warm-up: 0.1

student1:
  name: "distilbert-base-multilingual-cased"
  epochs: 15
  lr: 3.0e-5
  decay: 0.01
  patience: 3
  batch_size: 32
  output_dir: "outputs/checkpoints/student1_distilbert"
  warm-up: 0.1
  temperature: 3.0
  alpha: 0.7

student2:
  name: "nreimers/MiniLM-L6-H384-uncased"
  epochs: 40
  lr: 3.0e-5
  decay: 0.01 
  patience: 5 #3
  batch_size: 32
  output_dir: "outputs/checkpoints/student2_minilm_l6"
  warm-up: 0.1
  temperature: 3.0
  alpha: 0.3 #0.7

# student3:
#   name: "microsoft/MiniLM-L12-H384-uncased"
#   epochs: 15
#   lr: 1.0e-5
#   decay: 0.01
#   patience: 3
#   batch_size: 32
#   output_dir: "outputs/checkpoints/student3_minilm_l12"
#   warm-up: 0.1
#   temperature: 3.0
#   alpha: 0.7
  
paths:
  checkpoints: "outputs/checkpoints"
  logs: "outputs/logs"
  figures: "outputs/figures"

#### For testing purposes only #####

#Teacher Model
xlm-roBERTa-L:
  name: "FacebookAI/xlm-roberta-large" #for tokenizer
  checkpoint_dir: "outputs/checkpoints/Teacher_XLM-R-L"
  batch_size: 16

#Student model Directly fine tuned
minilm-l6-direct:
  name: "nreimers/MiniLM-L6-H384-uncased"
  checkpoint_dir: "outputs/checkpoints/MiniLM-L6-Direct-FineTune"
  batch_size: 32

distilmBERT-direct:
  name: "distilbert-base-multilingual-cased" #for tokenizer
  checkpoint_dir: "outputs/checkpoints/DistilmBERT-Direct-FineTune"
  batch_size: 32

#Student model distilled
minilm-l6-distilled: 
  name: "nreimers/MiniLM-L6-H384-uncased"
  checkpoint_dir: "outputs/checkpoints/MiniLM-L6-Distilled"
  batch_size: 32
distilmBERT-distilled:
  name: "distilbert-base-multilingual-cased" #for tokenizer
  checkpoint_dir: "outputs/checkpoints/DistilmBERT-Distilled"
  batch_size: 32
