class constants:
    TRAIN_SET = "train_set"
    TEST_SET = "test_set"
    EVAL_SET = "eval_set"
    SPLIT_NAME = "split_names"
    INTENT = "intent"
    DATASET = "dataset"
    LABEL = "label"
    TRAIN = "train"
    EVAL = "validation"
    TEST = "test"
    NAME = "name"
    COLUMNS = "columns"
    LANG = "languages"
    PRE_TRAIN_INTENTS = "pretrain_intents"
    REGISTRY_PATH = "registry_path"
